// <auto-generated />
namespace SuperCube3D_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddLoginCounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLoginCounter));
        
        string IMigrationMetadata.Id
        {
            get { return "202009042023188_AddLoginCounter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
